version: '2'
services:
  composer:
    build:
      context: ./composer
      dockerfile: Dockerfile
    volumes:
      - ./blog:/var/www/html/blog
      - ./composer/composer.sh:/var/www/html/blog/composer/composer.sh
    entrypoint: ['bash', '/var/www/html/blog/composer/composer.sh']
  php-fpm:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./blog:/var/www/html/blog
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./blog:/var/www/html/blog
      - ./nginx/ssl/certs/nginx-selfsigned.crt:/etc/ssl/server.crt
      - ./nginx/ssl/private/nginx-selfsigned.key:/etc/ssl/server.key
      - ./nginx/htpasswd:/etc/nginx/.htpasswd
    ports:
      - "3000:80"
      - "443:443"
    links:
      - php-fpm
